// ── KOSPI 시총 상위 100 ─────────────────────────────────────────────────────
export const KOSPI = [
  { symbol: "005930.KS", name: "삼성전자" },
  { symbol: "000660.KS", name: "SK하이닉스" },
  { symbol: "005380.KS", name: "현대차" },
  { symbol: "207940.KS", name: "삼성바이오로직스" },
  { symbol: "005490.KS", name: "POSCO홀딩스" },
  { symbol: "051910.KS", name: "LG화학" },
  { symbol: "035420.KS", name: "NAVER" },
  { symbol: "006400.KS", name: "삼성SDI" },
  { symbol: "028260.KS", name: "삼성물산" },
  { symbol: "012330.KS", name: "현대모비스" },
  { symbol: "035720.KS", name: "카카오" },
  { symbol: "000270.KS", name: "기아" },
  { symbol: "068270.KS", name: "셀트리온" },
  { symbol: "105560.KS", name: "KB금융" },
  { symbol: "055550.KS", name: "신한지주" },
  { symbol: "096770.KS", name: "SK이노베이션" },
  { symbol: "032830.KS", name: "삼성생명" },
  { symbol: "003550.KS", name: "LG" },
  { symbol: "017670.KS", name: "SK텔레콤" },
  { symbol: "316140.KS", name: "우리금융지주" },
  { symbol: "086790.KS", name: "하나금융지주" },
  { symbol: "009150.KS", name: "삼성전기" },
  { symbol: "018880.KS", name: "한화에어로스페이스" },
  { symbol: "004020.KS", name: "현대제철" },
  { symbol: "011070.KS", name: "LG이노텍" },
  { symbol: "010950.KS", name: "S-Oil" },
  { symbol: "024110.KS", name: "기업은행" },
  { symbol: "030200.KS", name: "KT" },
  { symbol: "066570.KS", name: "LG전자" },
  { symbol: "015760.KS", name: "한국전력" },
  { symbol: "000810.KS", name: "삼성화재" },
  { symbol: "034730.KS", name: "SK" },
  { symbol: "047810.KS", name: "한국항공우주" },
  { symbol: "003490.KS", name: "대한항공" },
  { symbol: "051900.KS", name: "LG생활건강" },
  { symbol: "039490.KS", name: "키움증권" },
  { symbol: "011200.KS", name: "HMM" },
  { symbol: "009830.KS", name: "한화솔루션" },
  { symbol: "000100.KS", name: "유한양행" },
  { symbol: "097950.KS", name: "CJ제일제당" },
  { symbol: "010140.KS", name: "삼성중공업" },
  { symbol: "034020.KS", name: "두산에너빌리티" },
  { symbol: "004990.KS", name: "롯데지주" },
  { symbol: "001040.KS", name: "CJ" },
  { symbol: "008770.KS", name: "호텔신라" },
  { symbol: "271560.KS", name: "오리온" },
  { symbol: "018260.KS", name: "삼성에스디에스" },
  { symbol: "033780.KS", name: "KT&G" },
  { symbol: "009540.KS", name: "HD한국조선해양" },
  { symbol: "042660.KS", name: "한화오션" },
  { symbol: "000720.KS", name: "현대건설" },
  { symbol: "006360.KS", name: "GS건설" },
  { symbol: "090430.KS", name: "아모레퍼시픽" },
  { symbol: "032640.KS", name: "LG유플러스" },
  { symbol: "036460.KS", name: "한국가스공사" },
  { symbol: "011170.KS", name: "롯데케미칼" },
  { symbol: "001450.KS", name: "현대해상" },
  { symbol: "005945.KS", name: "NH투자증권" },
  { symbol: "139480.KS", name: "이마트" },
  { symbol: "004170.KS", name: "신세계" },
  { symbol: "023530.KS", name: "롯데쇼핑" },
  { symbol: "161390.KS", name: "한국타이어앤테크놀로지" },
  { symbol: "011780.KS", name: "금호석유" },
  { symbol: "128940.KS", name: "한미약품" },
  { symbol: "021240.KS", name: "코웨이" },
  { symbol: "241560.KS", name: "두산밥캣" },
  { symbol: "267250.KS", name: "HD현대" },
  { symbol: "329180.KS", name: "현대중공업" },
  { symbol: "402340.KS", name: "SK스퀘어" },
  { symbol: "003230.KS", name: "삼양식품" },
  { symbol: "004800.KS", name: "효성" },
  { symbol: "007070.KS", name: "GS리테일" },
  { symbol: "282330.KS", name: "BGF리테일" },
  { symbol: "000880.KS", name: "한화" },
  { symbol: "003600.KS", name: "SK케미칼" },
  { symbol: "011790.KS", name: "SKC" },
  { symbol: "298050.KS", name: "효성첨단소재" },
  { symbol: "069620.KS", name: "대웅제약" },
  { symbol: "000670.KS", name: "영풍" },
  { symbol: "010620.KS", name: "현대미포조선" },
  { symbol: "145990.KS", name: "삼양사" },
  { symbol: "002380.KS", name: "KCC" },
  { symbol: "002600.KS", name: "남양유업" },
  { symbol: "069960.KS", name: "현대백화점" },
  { symbol: "000120.KS", name: "CJ대한통운" },
  { symbol: "001680.KS", name: "대상" },
  { symbol: "005850.KS", name: "에쓰오일" },
  { symbol: "007310.KS", name: "오뚜기" },
  { symbol: "180640.KS", name: "한진칼" },
  { symbol: "002790.KS", name: "아모레퍼시픽그룹" },
  { symbol: "009200.KS", name: "무림페이퍼" },
  { symbol: "078930.KS", name: "GS" },
  { symbol: "006800.KS", name: "대우증권" },
  { symbol: "036490.KS", name: "SK바이오사이언스" },
  { symbol: "326030.KS", name: "SK바이오팜" },
  { symbol: "000040.KS", name: "KY" },
  { symbol: "016360.KS", name: "삼성증권" },
  { symbol: "008560.KS", name: "메리츠화재" },
  { symbol: "138040.KS", name: "메리츠금융지주" },
  { symbol: "010130.KS", name: "고려아연" },
];

// ── KOSDAQ 시총 상위 100 ────────────────────────────────────────────────────
export const KOSDAQ = [
  { symbol: "247540.KQ", name: "에코프로비엠" },
  { symbol: "086520.KQ", name: "에코프로" },
  { symbol: "196170.KQ", name: "알테오젠" },
  { symbol: "091990.KQ", name: "셀트리온헬스케어" },
  { symbol: "041510.KQ", name: "에스엠" },
  { symbol: "035760.KQ", name: "CJ ENM" },
  { symbol: "263750.KQ", name: "펄어비스" },
  { symbol: "251270.KQ", name: "넷마블" },
  { symbol: "036570.KQ", name: "엔씨소프트" },
  { symbol: "293490.KQ", name: "카카오게임즈" },
  { symbol: "112040.KQ", name: "위메이드" },
  { symbol: "095340.KQ", name: "ISC" },
  { symbol: "145720.KQ", name: "덴티움" },
  { symbol: "214150.KQ", name: "클래시스" },
  { symbol: "053800.KQ", name: "안랩" },
  { symbol: "122870.KQ", name: "와이지엔터테인먼트" },
  { symbol: "035900.KQ", name: "JYP엔터테인먼트" },
  { symbol: "067310.KQ", name: "하나마이크론" },
  { symbol: "357780.KQ", name: "솔브레인" },
  { symbol: "039030.KQ", name: "이오테크닉스" },
  { symbol: "078340.KQ", name: "컴투스" },
  { symbol: "095660.KQ", name: "네오위즈" },
  { symbol: "067160.KQ", name: "아프리카TV" },
  { symbol: "039200.KQ", name: "오스코텍" },
  { symbol: "032500.KQ", name: "케이엠더블유" },
  { symbol: "222800.KQ", name: "심텍" },
  { symbol: "064760.KQ", name: "티씨케이" },
  { symbol: "041830.KQ", name: "인바디" },
  { symbol: "192400.KQ", name: "쿠쿠홀딩스" },
  { symbol: "063160.KQ", name: "종근당바이오" },
  { symbol: "237690.KQ", name: "에스티팜" },
  { symbol: "214870.KQ", name: "뷰노" },
  { symbol: "060150.KQ", name: "인터플렉스" },
  { symbol: "036200.KQ", name: "유니셈" },
  { symbol: "093240.KQ", name: "위닉스" },
  { symbol: "185750.KQ", name: "종근당" },
  { symbol: "060670.KQ", name: "한국콜마홀딩스" },
  { symbol: "054450.KQ", name: "텔레칩스" },
  { symbol: "091580.KQ", name: "상아프론테크" },
  { symbol: "140410.KQ", name: "메지온" },
  { symbol: "083500.KQ", name: "에프앤가이드" },
  { symbol: "950130.KQ", name: "엑세스바이오" },
  { symbol: "054620.KQ", name: "APS홀딩스" },
  { symbol: "101000.KQ", name: "오파스넷" },
  { symbol: "041460.KQ", name: "한국로봇" },
  { symbol: "045890.KQ", name: "파이오링크" },
  { symbol: "033230.KQ", name: "인성정보" },
  { symbol: "114810.KQ", name: "한솔아이원스" },
  { symbol: "071570.KQ", name: "코스맥스비티아이" },
  { symbol: "045280.KQ", name: "파세코" },
  { symbol: "002620.KQ", name: "제일파마홀딩스" },
  { symbol: "080600.KQ", name: "SIMPAC" },
  { symbol: "049800.KQ", name: "이엔코퍼레이션" },
  { symbol: "013310.KQ", name: "아진산업" },
  { symbol: "050860.KQ", name: "에이엔에스" },
  { symbol: "031820.KQ", name: "포스코엠텍" },
  { symbol: "048910.KQ", name: "대원미디어" },
  { symbol: "060310.KQ", name: "3S" },
  { symbol: "054040.KQ", name: "한국카본" },
  { symbol: "131970.KQ", name: "두산테스나" },
  { symbol: "108230.KQ", name: "YBM넷" },
  { symbol: "078020.KQ", name: "이베스트투자증권" },
  { symbol: "036800.KQ", name: "나이스정보통신" },
  { symbol: "119860.KQ", name: "커넥트웨이브" },
  { symbol: "050120.KQ", name: "ES큐브" },
  { symbol: "307280.KQ", name: "원바이오젠" },
  { symbol: "071090.KQ", name: "한국전자금융" },
  { symbol: "900290.KQ", name: "GRT" },
  { symbol: "204610.KQ", name: "티쓰리엔터테인먼트" },
  { symbol: "092200.KQ", name: "현대무벡스" },
  { symbol: "043090.KQ", name: "카이노스메드" },
  { symbol: "083790.KQ", name: "크리스탈지노믹스" },
  { symbol: "026890.KQ", name: "스틱인베스트먼트" },
  { symbol: "008900.KQ", name: "한국주강" },
  { symbol: "071200.KQ", name: "인피니트헬스케어" },
  { symbol: "049480.KQ", name: "오픈베이스" },
  { symbol: "049520.KQ", name: "유아이엘" },
  { symbol: "036750.KQ", name: "이에스에스" },
  { symbol: "078070.KQ", name: "DWS" },
  { symbol: "094820.KQ", name: "일리아스바이오" },
  { symbol: "060250.KQ", name: "NHN KCP" },
  { symbol: "041190.KQ", name: "우리기술투자" },
  { symbol: "041520.KQ", name: "이씨에스" },
  { symbol: "053160.KQ", name: "프리엠스" },
  { symbol: "130500.KQ", name: "GH신소재" },
  { symbol: "058450.KQ", name: "엔터파트너즈" },
  { symbol: "058970.KQ", name: "엠플러스" },
  { symbol: "041960.KQ", name: "블루베리NFT" },
  { symbol: "005760.KQ", name: "이수화학" },
  { symbol: "950170.KQ", name: "JTC" },
  { symbol: "039490.KQ", name: "키움증권" },
  { symbol: "035200.KQ", name: "프로스테믹스" },
  { symbol: "032640.KQ", name: "LG유플러스" },
  { symbol: "060680.KQ", name: "유비케어" },
  { symbol: "099430.KQ", name: "바이오플러스" },
  { symbol: "019210.KQ", name: "와이비엠넷" },
  { symbol: "063760.KQ", name: "이씨에스" },
  { symbol: "085370.KQ", name: "루트로닉" },
  { symbol: "214260.KQ", name: "일정실업" },
];

// ── 미국 시총 상위 100 ──────────────────────────────────────────────────────
export const US = [
  { symbol: "AAPL", name: "Apple" },
  { symbol: "MSFT", name: "Microsoft" },
  { symbol: "NVDA", name: "NVIDIA" },
  { symbol: "AMZN", name: "Amazon" },
  { symbol: "GOOGL", name: "Alphabet" },
  { symbol: "META", name: "Meta" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "AVGO", name: "Broadcom" },
  { symbol: "LLY", name: "Eli Lilly" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "V", name: "Visa" },
  { symbol: "UNH", name: "UnitedHealth" },
  { symbol: "XOM", name: "ExxonMobil" },
  { symbol: "MA", name: "Mastercard" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "COST", name: "Costco" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "ABBV", name: "AbbVie" },
  { symbol: "BAC", name: "Bank of America" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "AMD", name: "AMD" },
  { symbol: "MRK", name: "Merck" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "CVX", name: "Chevron" },
  { symbol: "PEP", name: "PepsiCo" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "TMO", name: "Thermo Fisher" },
  { symbol: "ACN", name: "Accenture" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "IBM", name: "IBM" },
  { symbol: "GS", name: "Goldman Sachs" },
  { symbol: "INTU", name: "Intuit" },
  { symbol: "QCOM", name: "Qualcomm" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "NOW", name: "ServiceNow" },
  { symbol: "MCD", name: "McDonald's" },
  { symbol: "GE", name: "GE" },
  { symbol: "PM", name: "Philip Morris" },
  { symbol: "VZ", name: "Verizon" },
  { symbol: "RTX", name: "RTX Corp" },
  { symbol: "AXP", name: "American Express" },
  { symbol: "T", name: "AT&T" },
  { symbol: "AMGN", name: "Amgen" },
  { symbol: "UPS", name: "UPS" },
  { symbol: "SYK", name: "Stryker" },
  { symbol: "CAT", name: "Caterpillar" },
  { symbol: "SPGI", name: "S&P Global" },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "DE", name: "Deere & Co" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "PFE", name: "Pfizer" },
  { symbol: "ISRG", name: "Intuitive Surgical" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "C", name: "Citigroup" },
  { symbol: "SCHW", name: "Charles Schwab" },
  { symbol: "HON", name: "Honeywell" },
  { symbol: "MMC", name: "Marsh McLennan" },
  { symbol: "LOW", name: "Lowe's" },
  { symbol: "ADI", name: "Analog Devices" },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "BX", name: "Blackstone" },
  { symbol: "CB", name: "Chubb" },
  { symbol: "VRTX", name: "Vertex Pharma" },
  { symbol: "ELV", name: "Elevance Health" },
  { symbol: "LMT", name: "Lockheed Martin" },
  { symbol: "BMY", name: "Bristol-Myers" },
  { symbol: "MDT", name: "Medtronic" },
  { symbol: "REGN", name: "Regeneron" },
  { symbol: "ADP", name: "ADP" },
  { symbol: "AMT", name: "American Tower" },
  { symbol: "CI", name: "Cigna" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "ETN", name: "Eaton Corp" },
  { symbol: "KLAC", name: "KLA Corp" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "TJX", name: "TJX Companies" },
  { symbol: "SO", name: "Southern Co" },
  { symbol: "ICE", name: "ICE" },
  { symbol: "PLD", name: "Prologis" },
  { symbol: "DUK", name: "Duke Energy" },
  { symbol: "MO", name: "Altria" },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "SBUX", name: "Starbucks" },
  { symbol: "ZTS", name: "Zoetis" },
  { symbol: "CME", name: "CME Group" },
  { symbol: "EQIX", name: "Equinix" },
  { symbol: "PANW", name: "Palo Alto Networks" },
  { symbol: "MCO", name: "Moody's" },
  { symbol: "APH", name: "Amphenol" },
  { symbol: "HCA", name: "HCA Healthcare" },
  { symbol: "TT", name: "Trane Technologies" },
  { symbol: "SHW", name: "Sherwin-Williams" },
  { symbol: "SNPS", name: "Synopsys" },
];

export const ALL_STOCKS = [
  ...KOSPI.map(s => ({ ...s, market: 'KOSPI', currency: '₩' })),
  ...KOSDAQ.map(s => ({ ...s, market: 'KOSDAQ', currency: '₩' })),
  ...US.map(s => ({ ...s, market: 'US', currency: '$' })),
];
